// Some strings that are used in various packages
package aws_strings

const (
	HASH               = "HASH"
	RANGE              = "RANGE"
	HASH_KEY_ELEMENT   = "HashKeyElement"
	RANGE_KEY_ELEMENT  = "RangeKeyElement"
	S                  = "S"
	N                  = "N"
	B                  = "B"
	BOOL               = "BOOL"
	NULL               = "NULL"
	L                  = "L"
	M                  = "M"
	SS                 = "SS"
	NS                 = "NS"
	BS                 = "BS"
	RETVAL_NONE        = "NONE"
	RETVAL_ALL_OLD     = "ALL_OLD"
	RETVAL_ALL_NEW     = "ALL_NEW"
	RETVAL_UPDATED_OLD = "UPDATED_OLD"
	RETVAL_UPDATED_NEW = "UPDATED_NEW"
	ALL                = "ALL"
	SIZE               = "SIZE"
	TOTAL              = "TOTAL"
	KEYS_ONLY          = "KEYS_ONLY"
	INCLUDE            = "INCLUDE"
	SELECT_ALL         = "ALL_ATTRIBUTES"
	SELECT_PROJECTED   = "ALL_PROJECTED_ATTRIBUTES"
	SELECT_SPECIFIC    = "SPECIFIC_ATTRIBUTES"
	SELECT_COUNT       = "COUNT"
	OP_EQ              = "EQ"
	OP_NE              = "NE"
	OP_LE              = "LE"
	OP_LT              = "LT"
	OP_GE              = "GE"
	OP_GT              = "GT"
	OP_NULL            = "NULL"
	OP_NOT_NULL        = "NOT_NULL"
	OP_CONTAINS        = "CONTAINS"
	OP_NOT_CONTAINS    = "NOT_CONTAINS"
	OP_BEGINS_WITH     = "BEGINS_WITH"
	OP_IN              = "IN"
	OP_BETWEEN         = "BETWEEN"
	ACTION_PUT         = "PUT"
	ACTION_DEL         = "DELETE"
	ACTION_ADD         = "ADD"
)
